export const FETCH_REPORTS_REQUEST = 'src/Reports/FETCH_REPORTS_REQUEST';
export const FETCH_REPORTS_SUCCESS = 'src/Reports/FETCH_REPORTS_SUCCESS';
export const FETCH_REPORTS_FAILURE = 'src/Reports/FETCH_REPORTS_FAILURE';
export const SET_REPORTS_RANGE = 'src/Reports/SET_REPORTS_RANGE';
export const SET_REPORTS_CUSTOM_DATES = 'src/Reports/SET_REPORTS_CUSTOM_DATES';
